### ISSUE TITLE
make the system that selects the speed for each robot based on the jumper

### ISSUE THREAD

**Issue by DBNines** [panthertech292/2021_r#20]
Right now we just use if statements inside the alignment functions. We could remake this with a function. The function would have an if statement to determine what bot we are on, then give out one of the 2 passed in  speed values.

**Comment by mark-has-it** [comment]
Definition:
public double get_ID_double_value(double v_production_value, double v_test_value) {
   private double v_l_production_value = v_production value;
   private double v_l_test_value = v_test_value;

    if(get_robotID == kproductionID) {
        return v_l_production_value;
    } else {
        return v_l_test_value;
    }
}

calling:
 set_motor_value(  get_ID_double_value(0.5, 0.6), get_ID_double_value(0.5,0.6) );
